### ISSUE TITLE
Further explanation of build-coq-demo.yml file

### ISSUE THREAD

**Issue by zunction** [erikmd/docker-coq-github-action-demo#10]
Thanks for this coq github action demo which helps entry users like me to get started by cloning your repository to test things out. With your template, I added a simple text file and push the updates up to my remote repository to see how github actions run (realised that when I used your template, github actions also get triggered in the initial commit).

In the CI workflow, I encountered an error when the jobs involving `4.09-flambda` with the error:
```
COQ_IMAGE=coqorg/coq:dev-ocaml-4.09-flambda
  Error response from daemon: manifest for coqorg/coq:dev-ocaml-4.09-flambda not found: manifest unknown: manifest unknown
```
Would you be able to explain this error? 

And then further explain the different jobs (`build` and `mathcomp`) in [build-coq-demo.yml](https://github.com/erikmd/docker-coq-github-action-demo/blob/master/.github/workflows/build-coq-demo.yml)? It seems to me `build` is installing `coq` versions `8.11` and `dev` on the OCaml versions `4.07, 4.09-flambda` and `mathcomp` just pulls the `mathcomp:1.10.0-coq-8.10, 8.11` images from docker hub. 

If we were to use the docker-mathcomp images, would it be possible for us to run a job to install other libraries, such as [deriving](https://github.com/arthuraa/deriving) in the image?

Many thanks and a happy new year!

**Comment by erikmd** [comment]
Hi @zunction, thanks for opening this issue!

> I encountered an error when the jobs involving `4.09-flambda`
> Would you be able to explain this error?

Good point: this just comes from the fact the combination (coq.dev, ocaml.4.09-flambda) is not rebuilt anymore in docker-coq
(cf. this line taken from https://github.com/coq-community/docker-coq/wiki#supported-tags :
`Coq dev: 4.05, 4.07-flambda, 4.10-flambda, 4.11-flambda`), and I just forgot to update the template in this GitHub repo docker-coq-github-action-demo, sorry for that… so, you should just replace `4.09-flambda` with `4.11-flambda` for example.

> And then further explain the different jobs (build and mathcomp) in build-coq-demo.yml?

Sure. All jobs pull a prebuilt image, the main difference being that:

1. in the (ocaml, coq) specified version, only Coq and Bignums are available,
    and the image is pulled ← https://hub.docker.com/r/coqorg/coq
2. in the mathcomp job, the image contains Coq, Bignums, as well as Math. Components (coq-mathcomp-character),
   and the image is pulled ← https://hub.docker.com/r/mathcomp/mathcomp or https://hub.docker.com/r/mathcomp/mathcomp-dev

So in a typical CI configuration, one should choose to include **only** one `build` like image **or** one `mathcomp` like image (if your library relies on mathcomp, so that the compilation can be done faster).

Note also that the (ocaml, coq) specification can be viewed as a Facade. Namely:

```yaml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.11'
          - dev
        ocaml_version:
          - '4.07-flambda'
          - '4.11-flambda'
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-demo.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
```

is equivalent to:

```yaml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.11-ocaml-4.07-flambda'
          - 'coqorg/coq:8.11-ocaml-4.11-flambda'
          - 'coqorg/coq:dev-ocaml-4.07-flambda'
          - 'coqorg/coq:dev-ocaml-4.11-flambda'
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-demo.opam'
          custom_image: ${{ matrix.image }}
```

but indeed I realize that some of my remarks above could be integrated somewhere in the repo, maybe in the README…

> If we were to use the docker-mathcomp images, would it be possible for us to run a job to install other libraries, such as deriving in the image?

Yes, definitely.

Either these additional dependencies are already specified in your `.opam` file, so they will be automatically installed by the command `opam install -y -j 2 $PACKAGE --deps-only`, cf. https://github.com/coq-community/docker-coq-action#install

Or you have some external dependencies, such as Debian packages or so, that you may want to install as well.

In this case, you could write something like:

```yaml
      before_install: |
        startGroup "Print opam config"
          opam config list; opam repo list; opam list
        endGroup
        startGroup "Install Debian packages"
          sudo apt-get update -y -q
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends emacs
        endGroup
```

Let me know if you have other questions.

> Many thanks and a happy new year!

Thanks! best wishes
